name = "ttrpg-mcp-on-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
DATA_BASE_URL = "https://ttrpg-mcp.tedt.org/data"
ALLOWED_ORIGINS = "*"
BUILD_VERSION = "dev"
BUILD_COMMIT = ""
BUILD_TIME = ""
